version: '3.5'

services:
 rabbitmq:
   container_name: rabbitmq
   hostname: rabbitmq
   image: rabbitmq:3.10-management
   ports:
      - 5672:5672
      - 15672:15672

 roach1:
   image: cockroachdb/cockroach:v22.1.1
   container_name: cockroach1
   hostname: cockroach1
   ports:
     - 26257:26257
     - 8080:8080
   command: start-single-node --insecure 
   volumes:
     - "//c/Users/fonius/cockroach-data/roach1:/cockroach/cockroach-data"
networks:
  twitterfeedservice_default:
    external: true